name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - uses: katyo/publish-crates@v2
      id: publish-crates
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: if my-crate published
      if: fromJSON(steps.publish-crates.outputs.published).*
      run: |
          LIST="${{ join(fromJSON(steps.publish-crates.outputs.published).*.name, ', ')) }}"
          echo "Published crates: $LIST"
